### ISSUE TITLE
Sign_in

### ISSUE THREAD

**Issue by knanahassouna1** [knanahassouna1/reddit#1]
- [ ] make sign_in structure (html)
- [ ] make sign_in style (css)
- [ ] make sign_in  dom (js)
- [ ] make sign_in validation (js)
- [ ] make sign_in request (js)
- [ ] make sign_in response (js)
